"""Guarantee ordering of wide-column CSV output.

"""
import enum


class GbqCsv(enum.Enum):
    """Class attributes form the order of CSV output.

    """
    DOMAIN = 0
    TITLE = 1
    ONLINE_SINCE = 2
    MEDIAN_LOAD_TIME = 3
    SPEED_PERCENTILE = 4
    ADULT_CONTENT = 5
    LINKS_IN_COUNT = 6
    LOCALE = 7
    ENCODING = 8
    DESCRIPTION = 9
    RANK = 10
    COUNTRY_CODE = 11
    COUNTRY_NAME = 12
    COUNTRY_RANK = 13
    DOMAIN_LINKINGIN = 14
    URL_LINKINGIN = 15
    IPV4_CONTINENT = 16
    IPV4_CONTINENT_CODE = 17
    IPV4_COUNTRY = 18
    IPV4_COUNTRY_CODE = 19
    IPV4_LATITUDE = 20
    IPV4_LONGITUDE = 21
    IPV4_ADDR = 22
    IPV4_ORG = 23
    IPV4_ISP = 24
    IPV6_CONTINENT = 25
    IPV6_CONTINENT_CODE = 26
    IPV6_COUNTRY = 27
    IPV6_COUNTRY_CODE = 28
    IPV6_LATITUDE = 29
    IPV6_LONGITUDE = 30
    IPV6_ADDR = 31
    IPV6_ORG = 32
    IPV6_ISP = 33
    TRAFFIC_TS = 34
    TRAFFIC_PAGE_VIEWS_PM = 35
    TRAFFIC_PAGE_VIEWS_USER = 36
    TRAFFIC_RANK = 37
    TRAFFIC_REACH = 38
    MNTH_1_VISITS_DT = 39
    MNTH_1_VISITS_UT = 40
    MNTH_3_VISITS_DT = 41
    MNTH_3_VISITS_UT = 42
    MNTH_1_RANK_DT = 43
    MNTH_1_RANK_UT = 44
    MNTH_3_RANK_DT = 45
    MNTH_3_RANK_UT = 46
    ANALYST_QAS_DATE = 47
    DOMAIN_DOWN_OR_PARKED = 48
    HAS_FORUM_OR_COMMENTS = 49
    HAS_RSS_FEED = 50
    LINKS_TO_OSP = 51
    LINKS_TO_TORRENTS = 52
    P2P_MAGNET_LINKS = 53
    REQUIRES_LOGIN = 54
    SEARCH_FEATURE = 55
